\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{uebungsblatt}[2010/05/19 Copyleft Thomas Holder, Tobias Heide, Marek Kubica, Michael Kerscher]

\input{uebungsblatt-requirements}
\input{uebungsblatt-options}

%% Load superclass

\LoadClass{scrartcl}

\input{uebungsblatt-commands}
\input{uebungsblatt-delayedhandlers}
\input{uebungsblatt-punkteverteilung}
\input{uebungsblatt-aufgabe}
\input{uebungsblatt-misc}

\input{uebungsblatt-style}
