\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{uebungsblatt}[2008/10/26 Copyleft Thomas Holder, Tobias Heide, Marek Kubica]

% Version Information: $Id$

\input{uebungsblatt-requirements}
\input{uebungsblatt-options}

%% Load superclass

\LoadClass{scrartcl}

\input{uebungsblatt-commands}
\input{uebungsblatt-delayedhandlers}
\input{uebungsblatt-punkteverteilung}
\input{uebungsblatt-aufgabe}
\input{uebungsblatt-misc}

\input{uebungsblatt-style}

% vi:ft=tex
